language: ruby
rvm:
  - 1.8.7
  - jruby-18mode
  - jruby-19mode
  - rbx-2.2
  - jruby-head
before_install:
  - ./fix-bundler.sh
matrix:
  allow_failures:
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: jruby-head
    - rvm: rbx-18mode
    - rvm: rbx-19mode
