language: ruby
rvm:
  - ree
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-18mode
  - jruby-19mode
  - rbx
  - jruby-head
before_install:
  - ./fix-bundler.sh
matrix:
  allow_failures:
    - rvm: jruby-18mode
    - rvm: jruby-head
